//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmic.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorLogID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public Nullable<int> ReckonFileID { get; set; }
        public Nullable<int> QboConnectID { get; set; }
        public string Controller { get; set; }
        public string Method { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorStackTrace { get; set; }
        public Nullable<System.DateTime> ErrorLogDate { get; set; }
    }
}
