//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmic.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSQLMaster
    {
        public int SqlID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string SqlServerName { get; set; }
        public string SqlDataBaseName { get; set; }
        public Nullable<bool> SqlAuthenticationMode { get; set; }
        public string SqlUserName { get; set; }
        public string SqlPassword { get; set; }
        public Nullable<System.DateTime> AddedDte { get; set; }
        public Nullable<System.DateTime> UpdatedDte { get; set; }
    }
}
