//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmic.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReckonDesktopMaster
    {
        public int ReckonFileID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string CompanyName { get; set; }
        public string LegalCompanyName { get; set; }
        public Nullable<bool> IsSampleCompany { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AdddeBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsUsingJobCosting { get; set; }
    }
}
