//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmic.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReckonDocument
    {
        public int ReckonDocumentID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ReckonFileID { get; set; }
        public Nullable<int> ScanInvoiceID { get; set; }
        public string TxnID { get; set; }
        public string ScanPdfPath { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string ReckonError { get; set; }
    }
}
