//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmic.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReckonFileUserAccess
    {
        public int ReckonUserAccessID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ReckonFileID { get; set; }
        public Nullable<bool> IsAccess { get; set; }
    }
}
