//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmic.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroVendor
    {
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> XeroConnectID { get; set; }
        public string XeroAccountID { get; set; }
        public string XeroVendorID { get; set; }
        public string DisplayNameField { get; set; }
        public string CityField { get; set; }
        public string CountrySubDivisionCodeField { get; set; }
        public string PostalCodeField { get; set; }
        public string CountryField { get; set; }
        public string PrimaryPhone { get; set; }
        public string PrimaryEmailAddr { get; set; }
        public string TaxIdentifier { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
