//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmic.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroTax
    {
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> XeroConnectID { get; set; }
        public string TaxName { get; set; }
        public string TaxID { get; set; }
    }
}
